server:
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:oracle:thin:@192.168.0.43:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format-sql: true
        use-sql-comments: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
file:
  upload_dir: C:\\uploads
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
 
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

#security
#spring ai
#kafka